using System.Data;
using System.Data.Common;
using FinancePro.Data.Context;
using FinancePro.Platform.Accounting;
using Microsoft.EntityFrameworkCore;

namespace FinancePro.Data.Accounting;

public sealed class SqlAnalyticAccountingService : IAnalyticAccountingService
{
    private readonly FinanceProDbContext _db; public SqlAnalyticAccountingService(FinanceProDbContext db)=>_db=db;
    public Task<IReadOnlyList<Department>> ListDepartmentsAsync(int companyId,CancellationToken ct=default)=>Query(companyId,"SELECT Id,CompanyId,Code,Name,Active FROM dbo.Departments WHERE CompanyId=@companyId ORDER BY Code",r=>new Department(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.GetBoolean(4)),ct);
    public Task<IReadOnlyList<AnalyticCostCenter>> ListCostCentersAsync(int companyId,CancellationToken ct=default)=>Query(companyId,@"SELECT c.Id,c.CompanyId,c.Code,c.Name,c.DepartmentId,d.Name,c.Active FROM dbo.CostCenters c LEFT JOIN dbo.Departments d ON d.Id=c.DepartmentId WHERE c.CompanyId=@companyId ORDER BY c.Code",r=>new AnalyticCostCenter(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetInt32(4),r.IsDBNull(5)?null:r.GetString(5),r.GetBoolean(6)),ct);
    public async Task SaveDepartmentAsync(SaveDepartmentRequest x,CancellationToken ct=default){if(x.CompanyId<=0||string.IsNullOrWhiteSpace(x.Code)||string.IsNullOrWhiteSpace(x.Name))throw new ArgumentException("Código e designação são obrigatórios.");await Exec(x.CompanyId,x.Id,@"IF @id IS NULL INSERT dbo.Departments(CompanyId,Code,Name,Active,CreatedAt,UpdatedAt) VALUES(@companyId,@code,@name,@active,SYSUTCDATETIME(),SYSUTCDATETIME()) ELSE UPDATE dbo.Departments SET Code=@code,Name=@name,Active=@active,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId",ct,("@code",x.Code.Trim().ToUpperInvariant()),("@name",x.Name.Trim()),("@active",x.Active));}
    public Task SetDepartmentActiveAsync(int c,int id,bool active,CancellationToken ct=default)=>Exec(c,id,"UPDATE dbo.Departments SET Active=@active,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId",ct,("@active",active));
    public Task AssignCostCenterDepartmentAsync(int c,int costCenterId,int? departmentId,CancellationToken ct=default)=>Exec(c,costCenterId,"UPDATE dbo.CostCenters SET DepartmentId=@departmentId,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId",ct,("@departmentId",departmentId));
    public async Task<IReadOnlyList<CostCenterPerformanceRow>> GetPerformanceAsync(int companyId,DateTime from,DateTime to,CancellationToken ct=default)
    {
        const string sql=@"SELECT c.Id,c.Code,c.Name,COALESCE(d.Name,''Sem departamento''),
COALESCE(b.Budgeted,0),COALESCE(cp.Committed,0),COALESCE(a.Realized,0),COALESCE(a.Revenue,0),COALESCE(a.Expense,0)
FROM dbo.CostCenters c LEFT JOIN dbo.Departments d ON d.Id=c.DepartmentId
OUTER APPLY(SELECT SUM(od.ValorPrevisto) Budgeted FROM dbo.OrcamentoDetalhes od JOIN dbo.Orcamentos o ON o.Id=od.OrcamentoId WHERE o.EmpresaId=@companyId AND od.CentroCusto=c.Code AND o.Ano BETWEEN YEAR(@from) AND YEAR(@to)) b
OUTER APPLY(SELECT SUM(cp.ValorTotal) Committed FROM dbo.Compras cp WHERE cp.EmpresaId=@companyId AND cp.CentroCusto=c.Code AND cp.Data BETWEEN @from AND @to AND cp.DataFatura IS NULL AND (cp.DataCotacao IS NOT NULL OR cp.DataOrdemCompra IS NOT NULL OR cp.DataRececao IS NOT NULL)) cp
OUTER APPLY(SELECT SUM(CASE WHEN ca.Nature='Devedora' THEN l.Debit-l.Credit ELSE l.Credit-l.Debit END) Realized,
SUM(CASE WHEN ca.Code LIKE '7%' THEN l.Credit-l.Debit ELSE 0 END) Revenue,
SUM(CASE WHEN ca.Code LIKE '6%' THEN l.Debit-l.Credit ELSE 0 END) Expense
FROM dbo.AccountingEntryLines l JOIN dbo.AccountingEntries e ON e.Id=l.AccountingEntryId JOIN dbo.EnterpriseChartAccounts ca ON ca.Id=l.AccountId WHERE e.CompanyId=@companyId AND l.CostCenterId=c.Id AND e.Status='Contabilizado' AND e.EntryDate BETWEEN @from AND @to) a
WHERE c.CompanyId=@companyId AND c.Active=1 ORDER BY c.Code";
        var list=new List<CostCenterPerformanceRow>();var cn=_db.Database.GetDbConnection();var close=cn.State!=ConnectionState.Open;if(close)await cn.OpenAsync(ct);try{await using var cmd=cn.CreateCommand();cmd.CommandText=sql;Add(cmd,"@companyId",companyId);Add(cmd,"@from",from.Date);Add(cmd,"@to",to.Date.AddDays(1).AddTicks(-1));await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var budget=r.GetDecimal(4);var committed=r.GetDecimal(5);var realized=r.GetDecimal(6);var revenue=r.GetDecimal(7);var expense=r.GetDecimal(8);var result=revenue-expense;var variance=budget-realized;var rate=budget==0?0:Math.Round(realized*100m/budget,1);list.Add(new(r.GetInt32(0),r.GetString(1),r.GetString(2),r.GetString(3),budget,committed,realized,revenue,expense,result,variance,rate));}return list;}finally{if(close)await cn.CloseAsync();}
    }
    public async Task<AnalyticAccountingSummary> GetSummaryAsync(int companyId,DateTime from,DateTime to,CancellationToken ct=default){var x=await GetPerformanceAsync(companyId,from,to,ct);return new(x.Sum(y=>y.Budgeted),x.Sum(y=>y.Committed),x.Sum(y=>y.Realized),x.Sum(y=>y.Revenue),x.Sum(y=>y.Expense),x.Sum(y=>y.Result),x.Sum(y=>y.Variance));}
    public Task<IReadOnlyList<ProjectRow>> ListProjectsAsync(int companyId,CancellationToken ct=default)=>Query(companyId,@"SELECT p.Id,p.Code,p.Name,COALESCE(cl.Nome,''),COALESCE(cc.Code+' - '+cc.Name,''),p.StartDate,p.EndDate,p.BudgetRevenue,p.BudgetCost,p.Status,
COALESCE((SELECT SUM(cr.Valor) FROM dbo.ContasReceber cr WHERE cr.EmpresaId=p.CompanyId AND cr.ProjectId=p.Id AND cr.Ativo=1 AND cr.ComercialEstado='Faturada'),0),
COALESCE((SELECT SUM(cp.Valor) FROM dbo.ContasPagar cp WHERE cp.EmpresaId=p.CompanyId AND cp.ProjectId=p.Id AND cp.Ativo=1),0)+COALESCE((SELECT SUM(c.ValorTotal) FROM dbo.Compras c WHERE c.EmpresaId=p.CompanyId AND c.ProjectId=p.Id AND c.Ativo=1 AND c.DataFatura IS NULL),0)+COALESCE((SELECT SUM(ABS(ms.Quantidade)*ms.CustoUnitario) FROM dbo.MovimentosStock ms WHERE ms.EmpresaId=p.CompanyId AND ms.ProjectId=p.Id AND ms.Ativo=1 AND ms.Tipo=1),0)
FROM dbo.Projects p LEFT JOIN dbo.Clientes cl ON cl.Id=p.ClientId LEFT JOIN dbo.CostCenters cc ON cc.Id=p.CostCenterId WHERE p.CompanyId=@companyId AND p.Active=1 ORDER BY p.StartDate DESC,p.Code",r=>{var rev=r.GetDecimal(10);var cost=r.GetDecimal(11);var result=rev-cost;return new ProjectRow(r.GetInt32(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetDateTime(5),r.IsDBNull(6)?null:r.GetDateTime(6),r.GetDecimal(7),r.GetDecimal(8),r.GetString(9),rev,cost,result,rev==0?0:Math.Round(result*100m/rev,1));},ct);
    public async Task SaveProjectAsync(SaveProjectRequest x,CancellationToken ct=default){if(x.CompanyId<=0||string.IsNullOrWhiteSpace(x.Code)||string.IsNullOrWhiteSpace(x.Name))throw new ArgumentException("Código e designação são obrigatórios.");await Exec(x.CompanyId,x.Id,@"IF @id IS NULL INSERT dbo.Projects(CompanyId,Code,Name,ClientId,CostCenterId,StartDate,EndDate,BudgetRevenue,BudgetCost,Status) VALUES(@companyId,@code,@name,@client,@costCenter,@start,@end,@revenue,@cost,@status) ELSE UPDATE dbo.Projects SET Code=@code,Name=@name,ClientId=@client,CostCenterId=@costCenter,StartDate=@start,EndDate=@end,BudgetRevenue=@revenue,BudgetCost=@cost,Status=@status,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId",ct,("@code",x.Code.Trim().ToUpperInvariant()),("@name",x.Name.Trim()),("@client",x.ClientId),("@costCenter",x.CostCenterId),("@start",x.StartDate.Date),("@end",x.EndDate?.Date),("@revenue",x.BudgetRevenue),("@cost",x.BudgetCost),("@status",x.Status));}
    public Task<IReadOnlyList<ProjectClientOption>> ListProjectClientsAsync(int companyId,CancellationToken ct=default)=>Query(companyId,"SELECT Id,Nome FROM dbo.Clientes WHERE EmpresaId=@companyId AND Ativo=1 ORDER BY Nome",r=>new ProjectClientOption(r.GetInt32(0),r.GetString(1)),ct);
    public async Task<IReadOnlyList<WorkOrderRow>> ListWorkOrdersAsync(int companyId,int? projectId=null,CancellationToken ct=default)
    {
        var sql=@"SELECT w.Id,w.ProjectId,p.Code+' - '+p.Name,w.Number,w.Description,w.OrderDate,w.DueDate,w.Status,w.EstimatedCost,w.ActualCost FROM dbo.WorkOrders w JOIN dbo.Projects p ON p.Id=w.ProjectId WHERE w.CompanyId=@companyId AND (@projectId IS NULL OR w.ProjectId=@projectId) ORDER BY w.OrderDate DESC,w.Number";
        var list=new List<WorkOrderRow>();var cn=_db.Database.GetDbConnection();var close=cn.State!=ConnectionState.Open;if(close)await cn.OpenAsync(ct);try{await using var cmd=cn.CreateCommand();cmd.CommandText=sql;Add(cmd,"@companyId",companyId);Add(cmd,"@projectId",projectId);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetDateTime(5),r.IsDBNull(6)?null:r.GetDateTime(6),r.GetString(7),r.GetDecimal(8),r.GetDecimal(9)));return list;}finally{if(close)await cn.CloseAsync();}
    }
    public async Task SaveWorkOrderAsync(SaveWorkOrderRequest x,CancellationToken ct=default){if(x.CompanyId<=0||x.ProjectId<=0||string.IsNullOrWhiteSpace(x.Number)||string.IsNullOrWhiteSpace(x.Description))throw new ArgumentException("Projeto, número e descrição são obrigatórios.");await Exec(x.CompanyId,x.Id,@"IF @id IS NULL INSERT dbo.WorkOrders(CompanyId,ProjectId,Number,Description,OrderDate,DueDate,Status,EstimatedCost) VALUES(@companyId,@project,@number,@description,@orderDate,@dueDate,@status,@estimated) ELSE UPDATE dbo.WorkOrders SET ProjectId=@project,Number=@number,Description=@description,OrderDate=@orderDate,DueDate=@dueDate,Status=@status,EstimatedCost=@estimated,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId",ct,("@project",x.ProjectId),("@number",x.Number.Trim().ToUpperInvariant()),("@description",x.Description.Trim()),("@orderDate",x.OrderDate.Date),("@dueDate",x.DueDate?.Date),("@status",x.Status),("@estimated",x.EstimatedCost));}
    private async Task<IReadOnlyList<T>> Query<T>(int companyId,string sql,Func<DbDataReader,T> map,CancellationToken ct){var a=new List<T>();var cn=_db.Database.GetDbConnection();var close=cn.State!=ConnectionState.Open;if(close)await cn.OpenAsync(ct);try{await using var cmd=cn.CreateCommand();cmd.CommandText=sql;Add(cmd,"@companyId",companyId);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))a.Add(map(r));return a;}finally{if(close)await cn.CloseAsync();}}
    private async Task Exec(int c,int? id,string sql,CancellationToken ct,params (string,object?)[] p){var cn=_db.Database.GetDbConnection();var close=cn.State!=ConnectionState.Open;if(close)await cn.OpenAsync(ct);try{await using var cmd=cn.CreateCommand();cmd.CommandText=sql;Add(cmd,"@companyId",c);Add(cmd,"@id",id);foreach(var x in p)Add(cmd,x.Item1,x.Item2);await cmd.ExecuteNonQueryAsync(ct);}finally{if(close)await cn.CloseAsync();}}
    private static void Add(DbCommand c,string n,object? v){var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}
}
