using FinancePro.Core.DTOs; using FinancePro.Core.Entities; using FinancePro.Core.Enums; using FinancePro.Data.Context; using FinancePro.Services.Interfaces; using Microsoft.EntityFrameworkCore;
namespace FinancePro.Services.Implementations;
public class StockService : IStockService
{
 private readonly FinanceProDbContext _db; public StockService(FinanceProDbContext db)=>_db=db;
 public async Task<IReadOnlyList<ProdutoStockDto>> ListarProdutosAsync(int e)=>await _db.Produtos.AsNoTracking().Where(x=>x.EmpresaId==e&&x.Ativo).OrderBy(x=>x.Nome).Select(x=>new ProdutoStockDto{Id=x.Id,Codigo=x.Codigo,Nome=x.Nome,Categoria=x.Categoria,Unidade=x.Unidade,StockAtual=x.StockAtual,StockMinimo=x.StockMinimo,CustoMedio=x.CustoMedio,PrecoVenda=x.PrecoVenda,ControlaStock=x.ControlaStock,Localizacao=x.Localizacao??""}).ToListAsync();
 public async Task<IReadOnlyList<MovimentoStockDto>> ListarMovimentosAsync(int e)=>await _db.MovimentosStock.AsNoTracking().Include(x=>x.Produto).Where(x=>x.EmpresaId==e).OrderByDescending(x=>x.Data).Take(200).Select(x=>new MovimentoStockDto{Data=x.Data,Produto=x.Produto.Nome,Tipo=x.Tipo.ToString(),Quantidade=x.Quantidade,CustoUnitario=x.CustoUnitario,SaldoApos=x.SaldoApos,DocumentoReferencia=x.DocumentoReferencia??""}).ToListAsync();
 public async Task CriarProdutoAsync(NovoProdutoDto d){ if(string.IsNullOrWhiteSpace(d.Codigo)||string.IsNullOrWhiteSpace(d.Nome)) throw new InvalidOperationException("Código e nome são obrigatórios."); if(d.PrecoVenda<0||d.StockMinimo<0)throw new InvalidOperationException("Preço de venda e stock mínimo não podem ser negativos."); if(await _db.Produtos.AnyAsync(x=>x.EmpresaId==d.EmpresaId&&x.Codigo==d.Codigo.Trim())) throw new InvalidOperationException("Já existe um item com este código."); _db.Produtos.Add(new Produto{EmpresaId=d.EmpresaId,Codigo=d.Codigo.Trim(),Nome=d.Nome.Trim(),Categoria=d.Categoria.Trim(),Unidade=string.IsNullOrWhiteSpace(d.Unidade)?"UN":d.Unidade.Trim(),StockMinimo=d.ControlaStock?d.StockMinimo:0,PrecoVenda=d.PrecoVenda,ControlaStock=d.ControlaStock,Localizacao=d.ControlaStock?d.Localizacao:null}); await _db.SaveChangesAsync(); }
 public async Task AtualizarProdutoAsync(int produtoId,NovoProdutoDto d){if(string.IsNullOrWhiteSpace(d.Codigo)||string.IsNullOrWhiteSpace(d.Nome))throw new InvalidOperationException("Código e nome são obrigatórios.");if(d.StockMinimo<0||d.PrecoVenda<0)throw new InvalidOperationException("Preço de venda e stock mínimo não podem ser negativos.");var p=await _db.Produtos.FirstOrDefaultAsync(x=>x.Id==produtoId&&x.EmpresaId==d.EmpresaId&&x.Ativo)??throw new InvalidOperationException("Produto ou serviço não encontrado.");if(p.ControlaStock&&!d.ControlaStock&&p.StockAtual!=0)throw new InvalidOperationException("Para converter um produto em serviço, o stock deve estar a zero.");var codigo=d.Codigo.Trim();if(await _db.Produtos.AnyAsync(x=>x.EmpresaId==d.EmpresaId&&x.Codigo==codigo&&x.Id!=produtoId))throw new InvalidOperationException("Já existe outro item com este código.");p.Codigo=codigo;p.Nome=d.Nome.Trim();p.Categoria=d.Categoria.Trim();p.Unidade=string.IsNullOrWhiteSpace(d.Unidade)?"UN":d.Unidade.Trim();p.StockMinimo=d.ControlaStock?d.StockMinimo:0;p.PrecoVenda=d.PrecoVenda;p.ControlaStock=d.ControlaStock;p.Localizacao=d.ControlaStock&& !string.IsNullOrWhiteSpace(d.Localizacao)?d.Localizacao.Trim():null;p.DataAtualizacao=DateTime.UtcNow;await _db.SaveChangesAsync();}
 public async Task ArquivarProdutoAsync(int empresaId,int produtoId){var p=await _db.Produtos.FirstOrDefaultAsync(x=>x.Id==produtoId&&x.EmpresaId==empresaId&&x.Ativo)??throw new InvalidOperationException("Produto não encontrado.");if(p.StockAtual!=0)throw new InvalidOperationException("Só é possível arquivar produtos com stock igual a zero.");p.Ativo=false;p.DataAtualizacao=DateTime.UtcNow;await _db.SaveChangesAsync();}
 public async Task MovimentarAsync(NovoMovimentoStockDto d){ if(d.Quantidade<=0) throw new InvalidOperationException("A quantidade deve ser maior que zero."); var p=await _db.Produtos.FirstOrDefaultAsync(x=>x.Id==d.ProdutoId&&x.EmpresaId==d.EmpresaId)??throw new InvalidOperationException("Produto não encontrado."); if(!p.ControlaStock)throw new InvalidOperationException("Serviços não possuem movimentos de stock."); var entrada=d.Tipo is TipoMovimentoStock.Entrada or TipoMovimentoStock.AjusteEntrada; if(!entrada&&p.StockAtual<d.Quantidade) throw new InvalidOperationException("Stock insuficiente para esta saída."); if(entrada){var novo=p.StockAtual+d.Quantidade; if(d.CustoUnitario>0) p.CustoMedio=novo==0?0:((p.StockAtual*p.CustoMedio)+(d.Quantidade*d.CustoUnitario))/novo; p.StockAtual=novo;} else p.StockAtual-=d.Quantidade; p.DataAtualizacao=DateTime.UtcNow; _db.MovimentosStock.Add(new MovimentoStock{EmpresaId=d.EmpresaId,ProdutoId=p.Id,Tipo=d.Tipo,Quantidade=d.Quantidade,CustoUnitario=d.CustoUnitario>0?d.CustoUnitario:p.CustoMedio,SaldoApos=p.StockAtual,DocumentoReferencia=d.DocumentoReferencia,Observacao=d.Observacao}); await _db.SaveChangesAsync(); }

 public async Task<IReadOnlyList<ProdutoRentabilidadeDto>> ListarRentabilidadeProdutosAsync(int empresaId)
 {
  var itens=await _db.VendaItens.AsNoTracking().Include(x=>x.ContaReceber).Include(x=>x.Produto)
   .Where(x=>x.ContaReceber.EmpresaId==empresaId&&x.ContaReceber.ComercialEstado=="Faturada")
   .Select(x=>new {x.ProdutoId,x.Produto.Codigo,Produto=x.Produto.Nome,x.Quantidade,Receita=x.Subtotal,CustoUnitario=x.Produto.CustoMedio}).ToListAsync();
  return itens.GroupBy(x=>new{x.ProdutoId,x.Codigo,x.Produto}).Select(g=>new ProdutoRentabilidadeDto{ProdutoId=g.Key.ProdutoId,Codigo=g.Key.Codigo,Produto=g.Key.Produto,QuantidadeVendida=g.Sum(x=>x.Quantidade),ReceitaLiquida=g.Sum(x=>x.Receita),CustoEstimado=g.Sum(x=>x.Quantidade*x.CustoUnitario)}).OrderByDescending(x=>x.MargemBruta).ToList();
 }
 public async Task<ResumoCustosMargensDto> ObterResumoCustosMargensAsync(int empresaId)
 {
  var lista=await ListarRentabilidadeProdutosAsync(empresaId);
  var inventario=await _db.Produtos.AsNoTracking().Where(x=>x.EmpresaId==empresaId&&x.Ativo&&x.ControlaStock).SumAsync(x=>(decimal?)(x.StockAtual*x.CustoMedio))??0m;
  return new ResumoCustosMargensDto{ReceitaLiquida=lista.Sum(x=>x.ReceitaLiquida),CustoProdutosVendidos=lista.Sum(x=>x.CustoEstimado),ValorInventario=inventario,ProdutosComMargemNegativa=lista.Count(x=>x.MargemBruta<0)};
 }
}
