using FinancePro.Core.DTOs; using FinancePro.Core.Entities; using FinancePro.Core.Enums; using FinancePro.Data.Context; using FinancePro.Services.Interfaces; using Microsoft.EntityFrameworkCore;
namespace FinancePro.Services.Implementations;
public class StockService : IStockService
{
 private readonly FinanceProDbContext _db; public StockService(FinanceProDbContext db)=>_db=db;
 public async Task<IReadOnlyList<ProdutoStockDto>> ListarProdutosAsync(int e)=>await _db.Produtos.AsNoTracking().Where(x=>x.EmpresaId==e&&x.Ativo).OrderBy(x=>x.Nome).Select(x=>new ProdutoStockDto{Id=x.Id,Codigo=x.Codigo,Nome=x.Nome,Categoria=x.Categoria,Unidade=x.Unidade,StockAtual=x.StockAtual,StockMinimo=x.StockMinimo,CustoMedio=x.CustoMedio,Localizacao=x.Localizacao??""}).ToListAsync();
 public async Task<IReadOnlyList<MovimentoStockDto>> ListarMovimentosAsync(int e)=>await _db.MovimentosStock.AsNoTracking().Include(x=>x.Produto).Where(x=>x.EmpresaId==e).OrderByDescending(x=>x.Data).Take(200).Select(x=>new MovimentoStockDto{Data=x.Data,Produto=x.Produto.Nome,Tipo=x.Tipo.ToString(),Quantidade=x.Quantidade,CustoUnitario=x.CustoUnitario,SaldoApos=x.SaldoApos,DocumentoReferencia=x.DocumentoReferencia??""}).ToListAsync();
 public async Task CriarProdutoAsync(NovoProdutoDto d){ if(string.IsNullOrWhiteSpace(d.Codigo)||string.IsNullOrWhiteSpace(d.Nome)) throw new InvalidOperationException("Código e nome são obrigatórios."); if(await _db.Produtos.AnyAsync(x=>x.EmpresaId==d.EmpresaId&&x.Codigo==d.Codigo.Trim())) throw new InvalidOperationException("Já existe um produto com este código."); _db.Produtos.Add(new Produto{EmpresaId=d.EmpresaId,Codigo=d.Codigo.Trim(),Nome=d.Nome.Trim(),Categoria=d.Categoria.Trim(),Unidade=string.IsNullOrWhiteSpace(d.Unidade)?"UN":d.Unidade.Trim(),StockMinimo=d.StockMinimo,Localizacao=d.Localizacao}); await _db.SaveChangesAsync(); }
 public async Task MovimentarAsync(NovoMovimentoStockDto d){ if(d.Quantidade<=0) throw new InvalidOperationException("A quantidade deve ser maior que zero."); var p=await _db.Produtos.FirstOrDefaultAsync(x=>x.Id==d.ProdutoId&&x.EmpresaId==d.EmpresaId)??throw new InvalidOperationException("Produto não encontrado."); var entrada=d.Tipo is TipoMovimentoStock.Entrada or TipoMovimentoStock.AjusteEntrada; if(!entrada&&p.StockAtual<d.Quantidade) throw new InvalidOperationException("Stock insuficiente para esta saída."); if(entrada){var novo=p.StockAtual+d.Quantidade; if(d.CustoUnitario>0) p.CustoMedio=novo==0?0:((p.StockAtual*p.CustoMedio)+(d.Quantidade*d.CustoUnitario))/novo; p.StockAtual=novo;} else p.StockAtual-=d.Quantidade; p.DataAtualizacao=DateTime.UtcNow; _db.MovimentosStock.Add(new MovimentoStock{EmpresaId=d.EmpresaId,ProdutoId=p.Id,Tipo=d.Tipo,Quantidade=d.Quantidade,CustoUnitario=d.CustoUnitario>0?d.CustoUnitario:p.CustoMedio,SaldoApos=p.StockAtual,DocumentoReferencia=d.DocumentoReferencia,Observacao=d.Observacao}); await _db.SaveChangesAsync(); }
}
