using System.Data;
using System.Data.Common;
using FinancePro.Data.Context;
using FinancePro.Platform.Administration;
using Microsoft.EntityFrameworkCore;

namespace FinancePro.Data.AdministrationMasterData;

public sealed class SqlAdministrationMasterDataStore : IAdministrationMasterDataStore
{
    private readonly FinanceProDbContext _dbContext;
    public SqlAdministrationMasterDataStore(FinanceProDbContext dbContext) => _dbContext = dbContext;

    public Task<IReadOnlyList<CostCenter>> ListCostCentersAsync(int companyId,CancellationToken ct=default)=>QueryAsync("SELECT Id,CompanyId,Code,Name,Active FROM dbo.CostCenters WHERE CompanyId=@companyId ORDER BY Code",companyId,r=>new CostCenter(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.GetBoolean(4)),ct);
    public Task<IReadOnlyList<TaxRate>> ListTaxRatesAsync(int companyId,CancellationToken ct=default)=>QueryAsync("SELECT Id,CompanyId,Code,Name,Rate,Active FROM dbo.TaxRates WHERE CompanyId=@companyId ORDER BY Code",companyId,r=>new TaxRate(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.GetDecimal(4),r.GetBoolean(5)),ct);
    public Task<IReadOnlyList<ChartAccount>> ListChartAccountsAsync(int companyId,CancellationToken ct=default)=>QueryAsync("SELECT Id,CompanyId,Code,Name,ParentId,AccountType,Nature,AllowsPosting,RequiresCostCenter,Active FROM dbo.EnterpriseChartAccounts WHERE CompanyId=@companyId ORDER BY Code",companyId,r=>new ChartAccount(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetInt32(4),r.GetString(5),r.GetString(6),r.GetBoolean(7),r.GetBoolean(8),r.GetBoolean(9)),ct);
    public Task<IReadOnlyList<DocumentSequence>> ListDocumentSequencesAsync(int companyId,CancellationToken ct=default)=>QueryAsync("SELECT Id,CompanyId,FiscalYear,Module,Prefix,CurrentNumber,Digits,RestartAnnually,Active FROM dbo.DocumentSequences WHERE CompanyId=@companyId ORDER BY FiscalYear DESC,Module",companyId,r=>new DocumentSequence(r.GetInt32(0),r.GetInt32(1),r.GetInt32(2),r.GetString(3),r.GetString(4),r.GetInt64(5),r.GetInt32(6),r.GetBoolean(7),r.GetBoolean(8)),ct);
    public Task<IReadOnlyList<FiscalObligation>> ListFiscalObligationsAsync(int companyId,CancellationToken ct=default)=>QueryAsync("SELECT Id,CompanyId,Code,Name,Category,DueDate,Frequency,Status,Notes,Active FROM dbo.FiscalObligations WHERE CompanyId=@companyId ORDER BY DueDate,Code",companyId,r=>new FiscalObligation(r.GetInt32(0),r.GetInt32(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetDateTime(5),r.GetString(6),r.GetString(7),r.IsDBNull(8)?null:r.GetString(8),r.GetBoolean(9)),ct);

    public Task SaveCostCenterAsync(SaveCostCenterRequest x,CancellationToken ct=default)=>ExecuteAsync(x.CompanyId,x.Id,@"IF @id IS NULL INSERT INTO dbo.CostCenters(CompanyId,Code,Name,Active,CreatedAt,UpdatedAt) VALUES(@companyId,@code,@name,@active,SYSUTCDATETIME(),SYSUTCDATETIME()); ELSE UPDATE dbo.CostCenters SET Code=@code,Name=@name,Active=@active,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId;",ct,("@code",x.Code),("@name",x.Name),("@active",x.Active));
    public Task SaveTaxRateAsync(SaveTaxRateRequest x,CancellationToken ct=default)=>ExecuteAsync(x.CompanyId,x.Id,@"IF @id IS NULL INSERT INTO dbo.TaxRates(CompanyId,Code,Name,Rate,Active,CreatedAt,UpdatedAt) VALUES(@companyId,@code,@name,@rate,@active,SYSUTCDATETIME(),SYSUTCDATETIME()); ELSE UPDATE dbo.TaxRates SET Code=@code,Name=@name,Rate=@rate,Active=@active,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId;",ct,("@code",x.Code),("@name",x.Name),("@rate",x.Rate),("@active",x.Active));
    public Task SaveChartAccountAsync(SaveChartAccountRequest x,CancellationToken ct=default)=>ExecuteAsync(x.CompanyId,x.Id,@"IF @id IS NULL INSERT INTO dbo.EnterpriseChartAccounts(CompanyId,Code,Name,ParentId,AccountType,Nature,AllowsPosting,RequiresCostCenter,Active,CreatedAt,UpdatedAt) VALUES(@companyId,@code,@name,@parentId,@accountType,@nature,@allowsPosting,@requiresCostCenter,@active,SYSUTCDATETIME(),SYSUTCDATETIME()); ELSE UPDATE dbo.EnterpriseChartAccounts SET Code=@code,Name=@name,ParentId=@parentId,AccountType=@accountType,Nature=@nature,AllowsPosting=@allowsPosting,RequiresCostCenter=@requiresCostCenter,Active=@active,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId;",ct,("@code",x.Code),("@name",x.Name),("@parentId",x.ParentId),("@accountType",x.AccountType),("@nature",x.Nature),("@allowsPosting",x.AllowsPosting),("@requiresCostCenter",x.RequiresCostCenter),("@active",x.Active));
    public Task SaveDocumentSequenceAsync(SaveDocumentSequenceRequest x,CancellationToken ct=default)=>ExecuteAsync(x.CompanyId,x.Id,@"IF @id IS NULL INSERT INTO dbo.DocumentSequences(CompanyId,FiscalYear,Module,Prefix,CurrentNumber,Digits,RestartAnnually,Active,CreatedAt,UpdatedAt) VALUES(@companyId,@fiscalYear,@module,@prefix,@currentNumber,@digits,@restartAnnually,@active,SYSUTCDATETIME(),SYSUTCDATETIME()); ELSE UPDATE dbo.DocumentSequences SET FiscalYear=@fiscalYear,Module=@module,Prefix=@prefix,CurrentNumber=@currentNumber,Digits=@digits,RestartAnnually=@restartAnnually,Active=@active,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId;",ct,("@fiscalYear",x.FiscalYear),("@module",x.Module),("@prefix",x.Prefix),("@currentNumber",x.CurrentNumber),("@digits",x.Digits),("@restartAnnually",x.RestartAnnually),("@active",x.Active));
    public Task SaveFiscalObligationAsync(SaveFiscalObligationRequest x,CancellationToken ct=default)=>ExecuteAsync(x.CompanyId,x.Id,@"IF @id IS NULL INSERT INTO dbo.FiscalObligations(CompanyId,Code,Name,Category,DueDate,Frequency,Status,Notes,Active,CreatedAt,UpdatedAt) VALUES(@companyId,@code,@name,@category,@dueDate,@frequency,@status,@notes,@active,SYSUTCDATETIME(),SYSUTCDATETIME()); ELSE UPDATE dbo.FiscalObligations SET Code=@code,Name=@name,Category=@category,DueDate=@dueDate,Frequency=@frequency,Status=@status,Notes=@notes,Active=@active,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId;",ct,("@code",x.Code),("@name",x.Name),("@category",x.Category),("@dueDate",x.DueDate),("@frequency",x.Frequency),("@status",x.Status),("@notes",x.Notes),("@active",x.Active));

    public Task SetCostCenterActiveAsync(int c,int id,bool a,CancellationToken ct=default)=>ToggleAsync("CostCenters",c,id,a,ct);
    public Task SetTaxRateActiveAsync(int c,int id,bool a,CancellationToken ct=default)=>ToggleAsync("TaxRates",c,id,a,ct);
    public Task SetChartAccountActiveAsync(int c,int id,bool a,CancellationToken ct=default)=>ToggleAsync("EnterpriseChartAccounts",c,id,a,ct);
    public Task SetDocumentSequenceActiveAsync(int c,int id,bool a,CancellationToken ct=default)=>ToggleAsync("DocumentSequences",c,id,a,ct);
    public Task SetFiscalObligationActiveAsync(int c,int id,bool a,CancellationToken ct=default)=>ToggleAsync("FiscalObligations",c,id,a,ct);

    private async Task<IReadOnlyList<T>> QueryAsync<T>(string sql,int companyId,Func<DbDataReader,T> map,CancellationToken ct){var list=new List<T>();var cn=_dbContext.Database.GetDbConnection();var close=cn.State!=ConnectionState.Open;if(close)await cn.OpenAsync(ct);try{await using var cmd=cn.CreateCommand();cmd.CommandText=sql;Add(cmd,"@companyId",companyId);await using var rd=await cmd.ExecuteReaderAsync(ct);while(await rd.ReadAsync(ct))list.Add(map(rd));return list;}finally{if(close)await cn.CloseAsync();}}
    private Task ToggleAsync(string table,int companyId,int id,bool active,CancellationToken ct)=>ExecuteAsync(companyId,id,$"UPDATE dbo.{table} SET Active=@active,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CompanyId=@companyId",ct,("@active",active));
    private async Task ExecuteAsync(int companyId,int? id,string sql,CancellationToken ct,params (string,object?)[] values){var cn=_dbContext.Database.GetDbConnection();var close=cn.State!=ConnectionState.Open;if(close)await cn.OpenAsync(ct);try{await using var cmd=cn.CreateCommand();cmd.CommandText=sql;Add(cmd,"@companyId",companyId);Add(cmd,"@id",id);foreach(var x in values)Add(cmd,x.Item1,x.Item2);await cmd.ExecuteNonQueryAsync(ct);}finally{if(close)await cn.CloseAsync();}}
    private static void Add(DbCommand c,string n,object? v){var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}
}
