IF OBJECT_ID('dbo.CostCenters','U') IS NULL
BEGIN
 CREATE TABLE dbo.CostCenters(
  Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CostCenters PRIMARY KEY,
  CompanyId INT NOT NULL, Code NVARCHAR(30) NOT NULL, Name NVARCHAR(150) NOT NULL,
  Active BIT NOT NULL CONSTRAINT DF_CostCenters_Active DEFAULT(1),
  CreatedAt DATETIME2 NOT NULL, UpdatedAt DATETIME2 NOT NULL,
  CONSTRAINT UQ_CostCenters_Company_Code UNIQUE(CompanyId,Code));
END;
GO
IF OBJECT_ID('dbo.TaxRates','U') IS NULL
BEGIN
 CREATE TABLE dbo.TaxRates(
  Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TaxRates PRIMARY KEY,
  CompanyId INT NOT NULL, Code NVARCHAR(30) NOT NULL, Name NVARCHAR(150) NOT NULL,
  Rate DECIMAL(9,4) NOT NULL, Active BIT NOT NULL CONSTRAINT DF_TaxRates_Active DEFAULT(1),
  CreatedAt DATETIME2 NOT NULL, UpdatedAt DATETIME2 NOT NULL,
  CONSTRAINT UQ_TaxRates_Company_Code UNIQUE(CompanyId,Code));
END;
GO
