using FinancePro.Platform.Administration;
using Xunit;
namespace FinancePro.Application.Tests.AdministrationMasterData;
public sealed class ChartAccountAndSequenceTests
{
 [Fact] public async Task SinteticaNaoPodeAceitarLancamentos(){var service=new AdministrationMasterDataService(new FakeStore());await Assert.ThrowsAsync<ArgumentException>(()=>service.SaveChartAccountAsync(new(1,null,"1","ATIVO",null,"Sintética","Devedora",true,false)));}
 [Fact] public async Task SequenciaNormalizaModuloEPrefixo(){var store=new FakeStore();var service=new AdministrationMasterDataService(store);await service.SaveDocumentSequenceAsync(new(1,null,2026," tes "," tes ",0,6,true));Assert.Equal("TES",store.Sequence!.Module);Assert.Equal("TES",store.Sequence.Prefix);}
 private sealed class FakeStore:IAdministrationMasterDataStore{public SaveDocumentSequenceRequest? Sequence;public Task<IReadOnlyList<CostCenter>> ListCostCentersAsync(int c,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<CostCenter>>([]);public Task<IReadOnlyList<TaxRate>> ListTaxRatesAsync(int c,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<TaxRate>>([]);public Task<IReadOnlyList<ChartAccount>> ListChartAccountsAsync(int c,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<ChartAccount>>([]);public Task<IReadOnlyList<DocumentSequence>> ListDocumentSequencesAsync(int c,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<DocumentSequence>>([]);public Task<IReadOnlyList<FiscalObligation>> ListFiscalObligationsAsync(int c,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<FiscalObligation>>([]);public Task SaveCostCenterAsync(SaveCostCenterRequest r,CancellationToken t=default)=>Task.CompletedTask;public Task SaveTaxRateAsync(SaveTaxRateRequest r,CancellationToken t=default)=>Task.CompletedTask;public Task SaveChartAccountAsync(SaveChartAccountRequest r,CancellationToken t=default)=>Task.CompletedTask;public Task SaveDocumentSequenceAsync(SaveDocumentSequenceRequest r,CancellationToken t=default){Sequence=r;return Task.CompletedTask;}public Task SaveFiscalObligationAsync(SaveFiscalObligationRequest r,CancellationToken t=default)=>Task.CompletedTask;public Task SetCostCenterActiveAsync(int c,int i,bool a,CancellationToken t=default)=>Task.CompletedTask;public Task SetTaxRateActiveAsync(int c,int i,bool a,CancellationToken t=default)=>Task.CompletedTask;public Task SetChartAccountActiveAsync(int c,int i,bool a,CancellationToken t=default)=>Task.CompletedTask;public Task SetDocumentSequenceActiveAsync(int c,int i,bool a,CancellationToken t=default)=>Task.CompletedTask;public Task SetFiscalObligationActiveAsync(int c,int i,bool a,CancellationToken t=default)=>Task.CompletedTask;}
}
