using System.Collections.ObjectModel;
using System.Windows.Input;
using FinancePro.Platform.Administration;
using FinancePro.UI.Common;

namespace FinancePro.UI.ViewModels;

public sealed class AdministrationMasterDataViewModel : ViewModelBase
{
    private readonly IAdministrationMasterDataService _service; private readonly int _companyId;
    private string _costCode="",_costName="",_taxCode="",_taxName="",_accountCode="",_accountName="",_accountType="Analítica",_accountNature="Devedora",_sequenceModule="",_sequencePrefix="",_fiscalCode="",_fiscalName="",_fiscalCategory="IVA",_fiscalFrequency="Mensal",_fiscalStatus="Pendente",_fiscalNotes="",_message="";
    private decimal _taxRate; private DateTime _fiscalDueDate=DateTime.Today.AddMonths(1); private FiscalComplianceSummary _fiscalSummary = new(0,0,0,0,0,100); private bool _busy,_accountAllowsPosting=true,_accountRequiresCostCenter,_sequenceRestartAnnually=true; private int _sequenceYear=DateTime.Today.Year,_sequenceDigits=6; private long _sequenceCurrentNumber;
    private int? _costId,_taxId,_accountId,_accountParentId,_sequenceId,_fiscalId; private bool _costActive=true,_taxActive=true,_accountActive=true,_sequenceActive=true,_fiscalActive=true;
    public ObservableCollection<CostCenter> CostCenters { get; }=new(); public ObservableCollection<TaxRate> TaxRates { get; }=new(); public ObservableCollection<ChartAccount> ChartAccounts { get; }=new(); public ObservableCollection<DocumentSequence> DocumentSequences { get; }=new(); public ObservableCollection<FiscalObligation> FiscalObligations { get; }=new();
    public IReadOnlyList<string> FiscalCategories { get; }=["IVA","Retenção","Imposto","Contribuição","Outro"]; public IReadOnlyList<string> FiscalFrequencies { get; }=["Única","Mensal","Trimestral","Semestral","Anual"]; public IReadOnlyList<string> FiscalStatuses { get; }=["Pendente","Cumprida","Atrasada","Cancelada"];
    public IReadOnlyList<string> AccountTypes { get; }=["Sintética","Analítica"]; public IReadOnlyList<string> AccountNatures { get; }=["Devedora","Credora"];
    public string CostCode{get=>_costCode;set=>SetProperty(ref _costCode,value);} public string CostName{get=>_costName;set=>SetProperty(ref _costName,value);} public string TaxCode{get=>_taxCode;set=>SetProperty(ref _taxCode,value);} public string TaxName{get=>_taxName;set=>SetProperty(ref _taxName,value);} public decimal TaxRate{get=>_taxRate;set=>SetProperty(ref _taxRate,value);}
    public string AccountCode{get=>_accountCode;set=>SetProperty(ref _accountCode,value);} public string AccountName{get=>_accountName;set=>SetProperty(ref _accountName,value);} public string AccountType{get=>_accountType;set{if(SetProperty(ref _accountType,value)&&value=="Sintética")AccountAllowsPosting=false;}} public string AccountNature{get=>_accountNature;set=>SetProperty(ref _accountNature,value);} public bool AccountAllowsPosting{get=>_accountAllowsPosting;set=>SetProperty(ref _accountAllowsPosting,value);} public bool AccountRequiresCostCenter{get=>_accountRequiresCostCenter;set=>SetProperty(ref _accountRequiresCostCenter,value);}
    public int SequenceYear{get=>_sequenceYear;set=>SetProperty(ref _sequenceYear,value);} public string SequenceModule{get=>_sequenceModule;set=>SetProperty(ref _sequenceModule,value);} public string SequencePrefix{get=>_sequencePrefix;set=>SetProperty(ref _sequencePrefix,value);} public long SequenceCurrentNumber{get=>_sequenceCurrentNumber;set=>SetProperty(ref _sequenceCurrentNumber,value);} public int SequenceDigits{get=>_sequenceDigits;set=>SetProperty(ref _sequenceDigits,value);} public bool SequenceRestartAnnually{get=>_sequenceRestartAnnually;set=>SetProperty(ref _sequenceRestartAnnually,value);}

    public string FiscalCode{get=>_fiscalCode;set=>SetProperty(ref _fiscalCode,value);} public string FiscalName{get=>_fiscalName;set=>SetProperty(ref _fiscalName,value);} public string FiscalCategory{get=>_fiscalCategory;set=>SetProperty(ref _fiscalCategory,value);} public DateTime FiscalDueDate{get=>_fiscalDueDate;set=>SetProperty(ref _fiscalDueDate,value);} public string FiscalFrequency{get=>_fiscalFrequency;set=>SetProperty(ref _fiscalFrequency,value);} public string FiscalStatus{get=>_fiscalStatus;set=>SetProperty(ref _fiscalStatus,value);} public string FiscalNotes{get=>_fiscalNotes;set=>SetProperty(ref _fiscalNotes,value);}
    public string Message{get=>_message;set=>SetProperty(ref _message,value);} public bool Busy{get=>_busy;set=>SetProperty(ref _busy,value);}
    public int ActiveCostCenters=>CostCenters.Count(x=>x.Active); public int ActiveTaxRates=>TaxRates.Count(x=>x.Active); public int ActiveAccounts=>ChartAccounts.Count(x=>x.Active); public int ActiveSequences=>DocumentSequences.Count(x=>x.Active); public int PendingFiscalObligations=>_fiscalSummary.Pending; public int OverdueFiscalObligations=>_fiscalSummary.Overdue; public int DueSoonFiscalObligations=>_fiscalSummary.DueSoon; public int CompletedFiscalObligations=>_fiscalSummary.Completed; public string FiscalComplianceRate=>$"{_fiscalSummary.ComplianceRate:N1}%";
    public ICommand RefreshCommand{get;} public ICommand SaveCostCenterCommand{get;} public ICommand SaveTaxRateCommand{get;} public ICommand SaveChartAccountCommand{get;} public ICommand SaveSequenceCommand{get;} public ICommand ToggleCostCenterCommand{get;} public ICommand ToggleTaxRateCommand{get;} public ICommand ToggleChartAccountCommand{get;} public ICommand ToggleSequenceCommand{get;} public ICommand SaveFiscalObligationCommand{get;} public ICommand ToggleFiscalObligationCommand{get;} public ICommand MarkFiscalCompletedCommand{get;} public ICommand MarkFiscalPendingCommand{get;} public ICommand EditCostCenterCommand{get;} public ICommand EditTaxRateCommand{get;} public ICommand EditChartAccountCommand{get;} public ICommand EditSequenceCommand{get;} public ICommand EditFiscalObligationCommand{get;}
    public AdministrationMasterDataViewModel(IAdministrationMasterDataService service,int companyId){_service=service;_companyId=companyId;RefreshCommand=new AsyncRelayCommand(_=>LoadAsync());SaveCostCenterCommand=new AsyncRelayCommand(_=>SaveCostCenterAsync());SaveTaxRateCommand=new AsyncRelayCommand(_=>SaveTaxRateAsync());SaveChartAccountCommand=new AsyncRelayCommand(_=>SaveChartAccountAsync());SaveSequenceCommand=new AsyncRelayCommand(_=>SaveSequenceAsync());ToggleCostCenterCommand=new AsyncRelayCommand(ToggleCostCenterAsync);ToggleTaxRateCommand=new AsyncRelayCommand(ToggleTaxRateAsync);ToggleChartAccountCommand=new AsyncRelayCommand(ToggleChartAccountAsync);ToggleSequenceCommand=new AsyncRelayCommand(ToggleSequenceAsync);SaveFiscalObligationCommand=new AsyncRelayCommand(_=>SaveFiscalObligationAsync());ToggleFiscalObligationCommand=new AsyncRelayCommand(ToggleFiscalObligationAsync);MarkFiscalCompletedCommand=new AsyncRelayCommand(p=>SetFiscalStatusAsync(p,"Cumprida"));MarkFiscalPendingCommand=new AsyncRelayCommand(p=>SetFiscalStatusAsync(p,"Pendente"));EditCostCenterCommand=new RelayCommand(EditCostCenter);EditTaxRateCommand=new RelayCommand(EditTaxRate);EditChartAccountCommand=new RelayCommand(EditChartAccount);EditSequenceCommand=new RelayCommand(EditSequence);EditFiscalObligationCommand=new RelayCommand(EditFiscalObligation);_=LoadAsync();}
    private async Task LoadAsync(){Busy=true;Message="";try{var c=await _service.ListCostCentersAsync(_companyId);var t=await _service.ListTaxRatesAsync(_companyId);var a=await _service.ListChartAccountsAsync(_companyId);var s=await _service.ListDocumentSequencesAsync(_companyId);var f=await _service.ListFiscalObligationsAsync(_companyId);_fiscalSummary=await _service.GetFiscalComplianceSummaryAsync(_companyId);Replace(CostCenters,c);Replace(TaxRates,t);Replace(ChartAccounts,a);Replace(DocumentSequences,s);Replace(FiscalObligations,f);OnPropertyChanged(nameof(ActiveCostCenters));OnPropertyChanged(nameof(ActiveTaxRates));OnPropertyChanged(nameof(ActiveAccounts));OnPropertyChanged(nameof(ActiveSequences));OnPropertyChanged(nameof(PendingFiscalObligations));OnPropertyChanged(nameof(OverdueFiscalObligations));OnPropertyChanged(nameof(DueSoonFiscalObligations));OnPropertyChanged(nameof(CompletedFiscalObligations));OnPropertyChanged(nameof(FiscalComplianceRate));}catch(Exception ex){Message=ex.Message;}finally{Busy=false;}}
    private async Task SaveCostCenterAsync(){try{await _service.SaveCostCenterAsync(new(_companyId,_costId,CostCode,CostName,_costActive));_costId=null;_costActive=true;CostCode=CostName="";Message="Centro de custo guardado.";await LoadAsync();}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveTaxRateAsync(){try{await _service.SaveTaxRateAsync(new(_companyId,_taxId,TaxCode,TaxName,TaxRate,_taxActive));_taxId=null;_taxActive=true;TaxCode=TaxName="";TaxRate=0;Message="Taxa de IVA guardada.";await LoadAsync();}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveChartAccountAsync(){try{await _service.SaveChartAccountAsync(new(_companyId,_accountId,AccountCode,AccountName,_accountParentId,AccountType,AccountNature,AccountAllowsPosting,AccountRequiresCostCenter,_accountActive));_accountId=_accountParentId=null;_accountActive=true;AccountCode=AccountName="";Message="Conta guardada.";await LoadAsync();}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveSequenceAsync(){try{await _service.SaveDocumentSequenceAsync(new(_companyId,_sequenceId,SequenceYear,SequenceModule,SequencePrefix,SequenceCurrentNumber,SequenceDigits,SequenceRestartAnnually,_sequenceActive));_sequenceId=null;_sequenceActive=true;SequenceModule=SequencePrefix="";SequenceCurrentNumber=0;Message="Sequência documental guardada.";await LoadAsync();}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveFiscalObligationAsync(){try{await _service.SaveFiscalObligationAsync(new(_companyId,_fiscalId,FiscalCode,FiscalName,FiscalCategory,FiscalDueDate,FiscalFrequency,FiscalStatus,FiscalNotes,_fiscalActive));_fiscalId=null;_fiscalActive=true;FiscalCode=FiscalName=FiscalNotes="";FiscalStatus="Pendente";Message="Obrigação fiscal guardada.";await LoadAsync();}catch(Exception ex){Message=ex.Message;}}
    private void EditCostCenter(object? p){if(p is CostCenter x){_costId=x.Id;_costActive=x.Active;CostCode=x.Code;CostName=x.Name;Message="Centro de custo carregado para edição.";}}
    private void EditTaxRate(object? p){if(p is TaxRate x){_taxId=x.Id;_taxActive=x.Active;TaxCode=x.Code;TaxName=x.Name;TaxRate=x.Rate;Message="Taxa carregada para edição.";}}
    private void EditChartAccount(object? p){if(p is ChartAccount x){_accountId=x.Id;_accountParentId=x.ParentId;_accountActive=x.Active;AccountCode=x.Code;AccountName=x.Name;AccountType=x.AccountType;AccountNature=x.Nature;AccountAllowsPosting=x.AllowsPosting;AccountRequiresCostCenter=x.RequiresCostCenter;Message="Conta carregada para edição.";}}
    private void EditSequence(object? p){if(p is DocumentSequence x){_sequenceId=x.Id;_sequenceActive=x.Active;SequenceYear=x.FiscalYear;SequenceModule=x.Module;SequencePrefix=x.Prefix;SequenceCurrentNumber=x.CurrentNumber;SequenceDigits=x.Digits;SequenceRestartAnnually=x.RestartAnnually;Message="Sequência carregada para edição.";}}
    private void EditFiscalObligation(object? p){if(p is FiscalObligation x){_fiscalId=x.Id;_fiscalActive=x.Active;FiscalCode=x.Code;FiscalName=x.Name;FiscalCategory=x.Category;FiscalDueDate=x.DueDate;FiscalFrequency=x.Frequency;FiscalStatus=x.Status;FiscalNotes=x.Notes??"";Message="Obrigação carregada para edição.";}}
    private async Task ToggleFiscalObligationAsync(object? p){if(p is FiscalObligation x){await _service.SetFiscalObligationActiveAsync(_companyId,x.Id,!x.Active);await LoadAsync();}}
    private async Task SetFiscalStatusAsync(object? p,string status){if(p is FiscalObligation x){try{await _service.SetFiscalObligationStatusAsync(_companyId,x.Id,status);Message=$"Obrigação marcada como {status.ToLowerInvariant()}.";await LoadAsync();}catch(Exception ex){Message=ex.Message;}}}
    private async Task ToggleCostCenterAsync(object? p){if(p is CostCenter x){await _service.SetCostCenterActiveAsync(_companyId,x.Id,!x.Active);await LoadAsync();}} private async Task ToggleTaxRateAsync(object? p){if(p is TaxRate x){await _service.SetTaxRateActiveAsync(_companyId,x.Id,!x.Active);await LoadAsync();}} private async Task ToggleChartAccountAsync(object? p){if(p is ChartAccount x){await _service.SetChartAccountActiveAsync(_companyId,x.Id,!x.Active);await LoadAsync();}} private async Task ToggleSequenceAsync(object? p){if(p is DocumentSequence x){await _service.SetDocumentSequenceActiveAsync(_companyId,x.Id,!x.Active);await LoadAsync();}}
    private static void Replace<T>(ObservableCollection<T> target,IEnumerable<T> source){target.Clear();foreach(var x in source)target.Add(x);}
}
