using System.Collections.ObjectModel;
using System.Windows.Input;
using FinancePro.Platform.HumanResources;
using FinancePro.UI.Common;

namespace FinancePro.UI.ViewModels;

public sealed class HumanResourcesViewModel : ViewModelBase
{
    private readonly IHumanResourcesService _service; private readonly int _companyId; private readonly List<EmployeeFinancialRow> _all=[];
    private EmployeeFinancialRow? _selected; private string _search="",_number="",_name="",_taxId="",_socialSecurity="",_department="",_costCenter="",_jobTitle="",_contractType="Efetivo",_bankName="",_iban="",_status="Ativo",_notes="",_message="";
    private DateTime _hireDate=DateTime.Today; private DateTime? _endDate; private decimal _baseSalary,_allowances,_deductions;
    private PayrollRunRow? _selectedPayroll; private int _payrollYear=DateTime.Today.Year,_payrollMonth=DateTime.Today.Month; private string _payrollNotes="";
    private PayrollLineRow? _selectedPayrollLine; private DateTime _paymentDate=DateTime.Today; private string _paymentReference="",_paymentNotes="";
    private EmployeeAdjustmentRow? _selectedAdjustment; private string _adjustmentType="Abono",_adjustmentCategory="Subsídio",_adjustmentDescription="",_adjustmentNotes=""; private decimal _adjustmentAmount; private DateTime _adjustmentStartDate=DateTime.Today; private DateTime? _adjustmentEndDate; private bool _adjustmentRecurring=true;
    private EmployeeAbsenceRow? _selectedAbsence; private string _absenceType="Férias",_absenceReason="",_absenceNotes=""; private DateTime _absenceStartDate=DateTime.Today,_absenceEndDate=DateTime.Today; private decimal _absenceDays=1,_absenceDeduction; private bool _absencePaid=true;
    private EmployeeAttendanceRow? _selectedAttendance; private DateTime _attendanceDate=DateTime.Today; private string _entryTime="08:00",_exitTime="17:00",_attendanceNotes=""; private decimal _regularHours=8,_overtimeHours,_overtimeAmount;
    private EmployeeLeaveBalanceRow? _selectedLeaveBalance; private int _leaveYear=DateTime.Today.Year; private decimal _entitledDays=22,_carriedDays; private string _leaveNotes="";
    private PayrollRuleRow? _selectedPayrollRule; private string _payrollRuleType="Imposto salarial",_payrollRuleName="",_payrollRuleNotes=""; private decimal _payrollRuleRate,_payrollRuleFixedAmount,_payrollRuleMinimumBase; private decimal? _payrollRuleMaximumBase; private DateTime _payrollRuleStartDate=new DateTime(DateTime.Today.Year,1,1); private DateTime? _payrollRuleEndDate;
    private EmployeeLoanRow? _selectedLoan; private string _loanType="Adiantamento salarial",_loanReference="",_loanNotes=""; private DateTime _loanGrantedDate=DateTime.Today,_loanFirstDeductionDate=new DateTime(DateTime.Today.Year,DateTime.Today.Month,1).AddMonths(1); private decimal _loanOriginalAmount,_loanOutstandingBalance,_loanInstallmentAmount;

    public ObservableCollection<EmployeeFinancialRow> Employees{get;}=[];
    public ObservableCollection<PayrollRunRow> PayrollRuns{get;}=[]; public ObservableCollection<PayrollLineRow> PayrollLines{get;}=[];
    public ObservableCollection<EmployeeAdjustmentRow> Adjustments{get;}=[];
    public ObservableCollection<EmployeeAbsenceRow> Absences{get;}=[];
    public ObservableCollection<EmployeeAttendanceRow> Attendance{get;}=[];
    public ObservableCollection<EmployeeLeaveBalanceRow> LeaveBalances{get;}=[];
    public ObservableCollection<PayrollRuleRow> PayrollRules{get;}=[];
    public ObservableCollection<EmployeeLoanRow> EmployeeLoans{get;}=[];
    public ObservableCollection<HumanResourcesDepartmentSummary> DepartmentSummaries{get;}=[];
    public IReadOnlyList<string> ContractTypes{get;}=["Efetivo","Prazo certo","Prazo incerto","Prestação de serviço","Estágio","Outro"];
    public IReadOnlyList<string> Statuses{get;}=["Ativo","Suspenso","Licença","Cessado"];
    public IReadOnlyList<string> AdjustmentTypes{get;}=["Abono","Desconto"]; public IReadOnlyList<string> AdjustmentCategories{get;}=["Subsídio","Prémio","Horas extraordinárias","Imposto","Segurança Social","Adiantamento","Falta","Outro"];
    public IReadOnlyList<string> AbsenceTypes{get;}=["Férias","Licença médica","Licença de maternidade","Licença de paternidade","Falta justificada","Falta injustificada","Outro"];
    public IReadOnlyList<string> PayrollRuleTypes{get;}=["Imposto salarial","Segurança Social - Trabalhador","Segurança Social - Entidade"];
    public IReadOnlyList<string> LoanTypes{get;}=["Adiantamento salarial","Empréstimo ao colaborador","Apoio social","Outro"];
    public ICommand RefreshCommand{get;} public ICommand NewCommand{get;} public ICommand SaveCommand{get;} public ICommand ArchiveCommand{get;}
    public ICommand GeneratePayrollCommand{get;} public ICommand ApprovePayrollCommand{get;}
    public ICommand RegisterPaymentCommand{get;} public ICommand PayEntirePayrollCommand{get;}
    public ICommand NewAdjustmentCommand{get;} public ICommand SaveAdjustmentCommand{get;} public ICommand ArchiveAdjustmentCommand{get;}
    public ICommand NewAbsenceCommand{get;} public ICommand SaveAbsenceCommand{get;} public ICommand ApproveAbsenceCommand{get;} public ICommand RejectAbsenceCommand{get;} public ICommand ArchiveAbsenceCommand{get;}
    public ICommand NewAttendanceCommand{get;} public ICommand SaveAttendanceCommand{get;} public ICommand ApproveAttendanceCommand{get;} public ICommand RejectAttendanceCommand{get;} public ICommand ArchiveAttendanceCommand{get;}
    public ICommand NewLeaveBalanceCommand{get;} public ICommand SaveLeaveBalanceCommand{get;} public ICommand ArchiveLeaveBalanceCommand{get;}
    public ICommand NewPayrollRuleCommand{get;} public ICommand SavePayrollRuleCommand{get;} public ICommand ArchivePayrollRuleCommand{get;}
    public ICommand NewLoanCommand{get;} public ICommand SaveLoanCommand{get;} public ICommand ActivateLoanCommand{get;} public ICommand SuspendLoanCommand{get;} public ICommand ArchiveLoanCommand{get;}
    public ICommand ExportEmployeesCommand{get;} public ICommand ExportPayrollCommand{get;} public ICommand ExportDepartmentsCommand{get;}
    public EmployeeFinancialRow? Selected{get=>_selected;set{if(SetProperty(ref _selected,value)){if(value is not null)LoadForm(value);_=LoadAdjustmentsAsync();_=LoadAbsencesAsync();_=LoadAttendanceAsync();_=LoadLeaveBalancesAsync();_=LoadEmployeeLoansAsync();}}}
    public PayrollRunRow? SelectedPayroll{get=>_selectedPayroll;set{if(SetProperty(ref _selectedPayroll,value))_=LoadPayrollLinesAsync();}}
    public PayrollLineRow? SelectedPayrollLine{get=>_selectedPayrollLine;set{if(SetProperty(ref _selectedPayrollLine,value)&&value is not null){PaymentDate=value.PaymentDate??DateTime.Today;PaymentReference=value.PaymentReference;PaymentNotes=value.Notes;}}}
    public EmployeeAdjustmentRow? SelectedAdjustment{get=>_selectedAdjustment;set{if(SetProperty(ref _selectedAdjustment,value)&&value is not null)LoadAdjustment(value);}}
    public EmployeeAbsenceRow? SelectedAbsence{get=>_selectedAbsence;set{if(SetProperty(ref _selectedAbsence,value)&&value is not null)LoadAbsence(value);}}
    public EmployeeAttendanceRow? SelectedAttendance{get=>_selectedAttendance;set{if(SetProperty(ref _selectedAttendance,value)&&value is not null)LoadAttendance(value);}}
    public EmployeeLeaveBalanceRow? SelectedLeaveBalance{get=>_selectedLeaveBalance;set{if(SetProperty(ref _selectedLeaveBalance,value)&&value is not null)LoadLeaveBalance(value);}}
    public PayrollRuleRow? SelectedPayrollRule{get=>_selectedPayrollRule;set{if(SetProperty(ref _selectedPayrollRule,value)&&value is not null)LoadPayrollRule(value);}}
    public EmployeeLoanRow? SelectedLoan{get=>_selectedLoan;set{if(SetProperty(ref _selectedLoan,value)&&value is not null)LoadLoan(value);}}
    public string Search{get=>_search;set{if(SetProperty(ref _search,value))ApplyFilter();}}
    public string EmployeeNumber{get=>_number;set=>SetProperty(ref _number,value);} public string FullName{get=>_name;set=>SetProperty(ref _name,value);} public string TaxId{get=>_taxId;set=>SetProperty(ref _taxId,value);} public string SocialSecurityNumber{get=>_socialSecurity;set=>SetProperty(ref _socialSecurity,value);} public string Department{get=>_department;set=>SetProperty(ref _department,value);} public string CostCenter{get=>_costCenter;set=>SetProperty(ref _costCenter,value);} public string JobTitle{get=>_jobTitle;set=>SetProperty(ref _jobTitle,value);} public string ContractType{get=>_contractType;set=>SetProperty(ref _contractType,value);} public string BankName{get=>_bankName;set=>SetProperty(ref _bankName,value);} public string Iban{get=>_iban;set=>SetProperty(ref _iban,value);} public string Status{get=>_status;set=>SetProperty(ref _status,value);} public string Notes{get=>_notes;set=>SetProperty(ref _notes,value);} public string Message{get=>_message;set=>SetProperty(ref _message,value);}
    public DateTime HireDate{get=>_hireDate;set=>SetProperty(ref _hireDate,value);} public DateTime? EndDate{get=>_endDate;set=>SetProperty(ref _endDate,value);} public decimal BaseSalary{get=>_baseSalary;set=>SetProperty(ref _baseSalary,value);} public decimal Allowances{get=>_allowances;set=>SetProperty(ref _allowances,value);} public decimal Deductions{get=>_deductions;set=>SetProperty(ref _deductions,value);}
    public int PayrollYear{get=>_payrollYear;set=>SetProperty(ref _payrollYear,value);} public int PayrollMonth{get=>_payrollMonth;set=>SetProperty(ref _payrollMonth,value);} public string PayrollNotes{get=>_payrollNotes;set=>SetProperty(ref _payrollNotes,value);}
    public DateTime PaymentDate{get=>_paymentDate;set=>SetProperty(ref _paymentDate,value);} public string PaymentReference{get=>_paymentReference;set=>SetProperty(ref _paymentReference,value);} public string PaymentNotes{get=>_paymentNotes;set=>SetProperty(ref _paymentNotes,value);}
    public string AdjustmentType{get=>_adjustmentType;set=>SetProperty(ref _adjustmentType,value);} public string AdjustmentCategory{get=>_adjustmentCategory;set=>SetProperty(ref _adjustmentCategory,value);} public string AdjustmentDescription{get=>_adjustmentDescription;set=>SetProperty(ref _adjustmentDescription,value);} public string AdjustmentNotes{get=>_adjustmentNotes;set=>SetProperty(ref _adjustmentNotes,value);} public decimal AdjustmentAmount{get=>_adjustmentAmount;set=>SetProperty(ref _adjustmentAmount,value);} public DateTime AdjustmentStartDate{get=>_adjustmentStartDate;set=>SetProperty(ref _adjustmentStartDate,value);} public DateTime? AdjustmentEndDate{get=>_adjustmentEndDate;set=>SetProperty(ref _adjustmentEndDate,value);} public bool AdjustmentRecurring{get=>_adjustmentRecurring;set=>SetProperty(ref _adjustmentRecurring,value);}
    public string AbsenceType{get=>_absenceType;set=>SetProperty(ref _absenceType,value);} public string AbsenceReason{get=>_absenceReason;set=>SetProperty(ref _absenceReason,value);} public string AbsenceNotes{get=>_absenceNotes;set=>SetProperty(ref _absenceNotes,value);} public DateTime AbsenceStartDate{get=>_absenceStartDate;set{if(SetProperty(ref _absenceStartDate,value)&&AbsenceEndDate<value)AbsenceEndDate=value;}} public DateTime AbsenceEndDate{get=>_absenceEndDate;set=>SetProperty(ref _absenceEndDate,value);} public decimal AbsenceDays{get=>_absenceDays;set=>SetProperty(ref _absenceDays,value);} public decimal AbsenceDeduction{get=>_absenceDeduction;set=>SetProperty(ref _absenceDeduction,value);} public bool AbsencePaid{get=>_absencePaid;set{if(SetProperty(ref _absencePaid,value)&&value)AbsenceDeduction=0;}}
    public DateTime AttendanceDate{get=>_attendanceDate;set=>SetProperty(ref _attendanceDate,value);} public string EntryTime{get=>_entryTime;set=>SetProperty(ref _entryTime,value);} public string ExitTime{get=>_exitTime;set=>SetProperty(ref _exitTime,value);} public string AttendanceNotes{get=>_attendanceNotes;set=>SetProperty(ref _attendanceNotes,value);} public decimal RegularHours{get=>_regularHours;set=>SetProperty(ref _regularHours,value);} public decimal OvertimeHours{get=>_overtimeHours;set=>SetProperty(ref _overtimeHours,value);} public decimal OvertimeAmount{get=>_overtimeAmount;set=>SetProperty(ref _overtimeAmount,value);}
    public int LeaveYear{get=>_leaveYear;set=>SetProperty(ref _leaveYear,value);} public decimal EntitledDays{get=>_entitledDays;set=>SetProperty(ref _entitledDays,value);} public decimal CarriedDays{get=>_carriedDays;set=>SetProperty(ref _carriedDays,value);} public string LeaveNotes{get=>_leaveNotes;set=>SetProperty(ref _leaveNotes,value);}
    public string PayrollRuleType{get=>_payrollRuleType;set=>SetProperty(ref _payrollRuleType,value);} public string PayrollRuleName{get=>_payrollRuleName;set=>SetProperty(ref _payrollRuleName,value);} public string PayrollRuleNotes{get=>_payrollRuleNotes;set=>SetProperty(ref _payrollRuleNotes,value);} public decimal PayrollRuleRate{get=>_payrollRuleRate;set=>SetProperty(ref _payrollRuleRate,value);} public decimal PayrollRuleFixedAmount{get=>_payrollRuleFixedAmount;set=>SetProperty(ref _payrollRuleFixedAmount,value);} public decimal PayrollRuleMinimumBase{get=>_payrollRuleMinimumBase;set=>SetProperty(ref _payrollRuleMinimumBase,value);} public decimal? PayrollRuleMaximumBase{get=>_payrollRuleMaximumBase;set=>SetProperty(ref _payrollRuleMaximumBase,value);} public DateTime PayrollRuleStartDate{get=>_payrollRuleStartDate;set=>SetProperty(ref _payrollRuleStartDate,value);} public DateTime? PayrollRuleEndDate{get=>_payrollRuleEndDate;set=>SetProperty(ref _payrollRuleEndDate,value);}
    public string LoanType{get=>_loanType;set=>SetProperty(ref _loanType,value);} public string LoanReference{get=>_loanReference;set=>SetProperty(ref _loanReference,value);} public string LoanNotes{get=>_loanNotes;set=>SetProperty(ref _loanNotes,value);} public DateTime LoanGrantedDate{get=>_loanGrantedDate;set=>SetProperty(ref _loanGrantedDate,value);} public DateTime LoanFirstDeductionDate{get=>_loanFirstDeductionDate;set=>SetProperty(ref _loanFirstDeductionDate,value);} public decimal LoanOriginalAmount{get=>_loanOriginalAmount;set{if(SetProperty(ref _loanOriginalAmount,value)&&SelectedLoan is null)LoanOutstandingBalance=value;}} public decimal LoanOutstandingBalance{get=>_loanOutstandingBalance;set=>SetProperty(ref _loanOutstandingBalance,value);} public decimal LoanInstallmentAmount{get=>_loanInstallmentAmount;set=>SetProperty(ref _loanInstallmentAmount,value);}
    public int ActiveEmployees=>Employees.Count(x=>x.Status=="Ativo"); public decimal TotalBaseSalary=>Employees.Where(x=>x.Status=="Ativo").Sum(x=>x.BaseSalary); public decimal TotalAllowances=>Employees.Where(x=>x.Status=="Ativo").Sum(x=>x.Allowances); public decimal NetMonthlyPayroll=>Employees.Where(x=>x.Status=="Ativo").Sum(x=>x.NetMonthly);

    public HumanResourcesViewModel(IHumanResourcesService service,int companyId){_service=service;_companyId=companyId;RefreshCommand=new AsyncRelayCommand(_=>LoadAsync());NewCommand=new AsyncRelayCommand(_=>{ClearForm();return Task.CompletedTask;});SaveCommand=new AsyncRelayCommand(_=>SaveAsync());ArchiveCommand=new AsyncRelayCommand(_=>ArchiveAsync());GeneratePayrollCommand=new AsyncRelayCommand(_=>GeneratePayrollAsync());ApprovePayrollCommand=new AsyncRelayCommand(_=>ApprovePayrollAsync());RegisterPaymentCommand=new AsyncRelayCommand(_=>RegisterPaymentAsync());PayEntirePayrollCommand=new AsyncRelayCommand(_=>PayEntirePayrollAsync());NewAdjustmentCommand=new AsyncRelayCommand(_=>{ClearAdjustment();return Task.CompletedTask;});SaveAdjustmentCommand=new AsyncRelayCommand(_=>SaveAdjustmentAsync());ArchiveAdjustmentCommand=new AsyncRelayCommand(_=>ArchiveAdjustmentAsync());NewAbsenceCommand=new AsyncRelayCommand(_=>{ClearAbsence();return Task.CompletedTask;});SaveAbsenceCommand=new AsyncRelayCommand(_=>SaveAbsenceAsync());ApproveAbsenceCommand=new AsyncRelayCommand(_=>SetAbsenceStatusAsync("Aprovada"));RejectAbsenceCommand=new AsyncRelayCommand(_=>SetAbsenceStatusAsync("Rejeitada"));ArchiveAbsenceCommand=new AsyncRelayCommand(_=>ArchiveAbsenceAsync());NewAttendanceCommand=new AsyncRelayCommand(_=>{ClearAttendance();return Task.CompletedTask;});SaveAttendanceCommand=new AsyncRelayCommand(_=>SaveAttendanceAsync());ApproveAttendanceCommand=new AsyncRelayCommand(_=>SetAttendanceStatusAsync("Aprovado"));RejectAttendanceCommand=new AsyncRelayCommand(_=>SetAttendanceStatusAsync("Rejeitado"));ArchiveAttendanceCommand=new AsyncRelayCommand(_=>ArchiveAttendanceAsync());NewLeaveBalanceCommand=new AsyncRelayCommand(_=>{ClearLeaveBalance();return Task.CompletedTask;});SaveLeaveBalanceCommand=new AsyncRelayCommand(_=>SaveLeaveBalanceAsync());ArchiveLeaveBalanceCommand=new AsyncRelayCommand(_=>ArchiveLeaveBalanceAsync());NewPayrollRuleCommand=new AsyncRelayCommand(_=>{ClearPayrollRule();return Task.CompletedTask;});SavePayrollRuleCommand=new AsyncRelayCommand(_=>SavePayrollRuleAsync());ArchivePayrollRuleCommand=new AsyncRelayCommand(_=>ArchivePayrollRuleAsync());NewLoanCommand=new AsyncRelayCommand(_=>{ClearLoan();return Task.CompletedTask;});SaveLoanCommand=new AsyncRelayCommand(_=>SaveLoanAsync());ActivateLoanCommand=new AsyncRelayCommand(_=>SetLoanStatusAsync("Ativo"));SuspendLoanCommand=new AsyncRelayCommand(_=>SetLoanStatusAsync("Suspenso"));ArchiveLoanCommand=new AsyncRelayCommand(_=>ArchiveLoanAsync());ExportEmployeesCommand=new RelayCommand(_=>ExportEmployees());ExportPayrollCommand=new RelayCommand(_=>ExportPayroll());ExportDepartmentsCommand=new RelayCommand(_=>ExportDepartments());_=LoadAsync();}
    private async Task LoadAsync(){try{var rows=await _service.ListEmployeesAsync(_companyId);var runs=await _service.ListPayrollRunsAsync(_companyId);var rules=await _service.ListPayrollRulesAsync(_companyId);_all.Clear();_all.AddRange(rows);ApplyFilter();PayrollRuns.Clear();foreach(var run in runs)PayrollRuns.Add(run);PayrollRules.Clear();foreach(var rule in rules)PayrollRules.Add(rule);await LoadPayrollLinesAsync();Message=$"{rows.Count} colaborador(es) carregado(s).";}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveAsync(){try{await _service.SaveEmployeeAsync(new(_companyId,Selected?.Id,EmployeeNumber,FullName,TaxId,SocialSecurityNumber,Department,CostCenter,JobTitle,ContractType,HireDate,EndDate,BaseSalary,Allowances,Deductions,BankName,Iban,Status,Notes));ClearForm();await LoadAsync();Message="Colaborador guardado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task ArchiveAsync(){if(Selected is null){Message="Selecione um colaborador.";return;}try{await _service.ArchiveEmployeeAsync(_companyId,Selected.Id);ClearForm();await LoadAsync();Message="Colaborador arquivado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task LoadPayrollLinesAsync(){PayrollLines.Clear();if(SelectedPayroll is null)return;try{var rows=await _service.ListPayrollLinesAsync(_companyId,SelectedPayroll.Id);foreach(var row in rows)PayrollLines.Add(row);}catch(Exception ex){Message=ex.Message;}}
    private async Task GeneratePayrollAsync(){try{await _service.GeneratePayrollAsync(_companyId,PayrollYear,PayrollMonth,PayrollNotes);PayrollNotes="";await LoadAsync();Message="Folha salarial gerada.";}catch(Exception ex){Message=ex.Message;}}
    private async Task ApprovePayrollAsync(){if(SelectedPayroll is null){Message="Selecione uma folha salarial.";return;}try{await _service.ApprovePayrollAsync(_companyId,SelectedPayroll.Id);await LoadAsync();Message="Folha salarial aprovada.";}catch(Exception ex){Message=ex.Message;}}
    private async Task RegisterPaymentAsync(){if(SelectedPayrollLine is null){Message="Selecione o colaborador na folha.";return;}try{await _service.RegisterPayrollPaymentAsync(_companyId,SelectedPayrollLine.Id,PaymentDate,PaymentReference,PaymentNotes);ClearPayment();await LoadAsync();Message="Pagamento salarial registado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task PayEntirePayrollAsync(){if(SelectedPayroll is null){Message="Selecione uma folha salarial.";return;}try{await _service.PayEntirePayrollAsync(_companyId,SelectedPayroll.Id,PaymentDate,PaymentReference);ClearPayment();await LoadAsync();Message="Folha salarial marcada como paga.";}catch(Exception ex){Message=ex.Message;}}
    private async Task LoadAdjustmentsAsync(){Adjustments.Clear();if(Selected is null)return;try{var rows=await _service.ListEmployeeAdjustmentsAsync(_companyId,Selected.Id);foreach(var row in rows)Adjustments.Add(row);}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveAdjustmentAsync(){if(Selected is null){Message="Selecione um colaborador.";return;}try{await _service.SaveEmployeeAdjustmentAsync(new(_companyId,SelectedAdjustment?.Id,Selected.Id,AdjustmentType,AdjustmentCategory,AdjustmentDescription,AdjustmentAmount,AdjustmentStartDate,AdjustmentEndDate,AdjustmentRecurring,AdjustmentNotes));ClearAdjustment();await LoadAdjustmentsAsync();Message="Componente remuneratório guardado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task ArchiveAdjustmentAsync(){if(SelectedAdjustment is null){Message="Selecione um componente remuneratório.";return;}try{await _service.ArchiveEmployeeAdjustmentAsync(_companyId,SelectedAdjustment.Id);ClearAdjustment();await LoadAdjustmentsAsync();Message="Componente arquivado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task LoadAbsencesAsync(){Absences.Clear();if(Selected is null)return;try{var rows=await _service.ListEmployeeAbsencesAsync(_companyId,Selected.Id);foreach(var row in rows)Absences.Add(row);}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveAbsenceAsync(){if(Selected is null){Message="Selecione um colaborador.";return;}try{await _service.SaveEmployeeAbsenceAsync(new(_companyId,SelectedAbsence?.Id,Selected.Id,AbsenceType,AbsenceStartDate,AbsenceEndDate,AbsenceDays,AbsencePaid,AbsenceDeduction,AbsenceReason,AbsenceNotes));ClearAbsence();await LoadAbsencesAsync();Message="Ausência guardada e pendente de decisão.";}catch(Exception ex){Message=ex.Message;}}
    private async Task SetAbsenceStatusAsync(string status){if(SelectedAbsence is null){Message="Selecione uma ausência.";return;}try{await _service.SetEmployeeAbsenceStatusAsync(_companyId,SelectedAbsence.Id,status);ClearAbsence();await LoadAbsencesAsync();Message=$"Ausência {status.ToLowerInvariant()}.";}catch(Exception ex){Message=ex.Message;}}
    private async Task ArchiveAbsenceAsync(){if(SelectedAbsence is null){Message="Selecione uma ausência.";return;}try{await _service.ArchiveEmployeeAbsenceAsync(_companyId,SelectedAbsence.Id);ClearAbsence();await LoadAbsencesAsync();Message="Ausência arquivada.";}catch(Exception ex){Message=ex.Message;}}
    private async Task LoadAttendanceAsync(){Attendance.Clear();if(Selected is null)return;try{var rows=await _service.ListEmployeeAttendanceAsync(_companyId,Selected.Id);foreach(var row in rows)Attendance.Add(row);}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveAttendanceAsync(){if(Selected is null){Message="Selecione um colaborador.";return;}try{await _service.SaveEmployeeAttendanceAsync(new(_companyId,SelectedAttendance?.Id,Selected.Id,AttendanceDate,EntryTime,ExitTime,RegularHours,OvertimeHours,OvertimeAmount,AttendanceNotes));ClearAttendance();await LoadAttendanceAsync();Message="Registo de assiduidade guardado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task SetAttendanceStatusAsync(string status){if(SelectedAttendance is null){Message="Selecione um registo de assiduidade.";return;}try{await _service.SetEmployeeAttendanceStatusAsync(_companyId,SelectedAttendance.Id,status);ClearAttendance();await LoadAttendanceAsync();Message=$"Registo {status.ToLowerInvariant()}.";}catch(Exception ex){Message=ex.Message;}}
    private async Task ArchiveAttendanceAsync(){if(SelectedAttendance is null){Message="Selecione um registo de assiduidade.";return;}try{await _service.ArchiveEmployeeAttendanceAsync(_companyId,SelectedAttendance.Id);ClearAttendance();await LoadAttendanceAsync();Message="Registo de assiduidade arquivado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task LoadLeaveBalancesAsync(){LeaveBalances.Clear();if(Selected is null)return;try{var rows=await _service.ListEmployeeLeaveBalancesAsync(_companyId,Selected.Id);foreach(var row in rows)LeaveBalances.Add(row);}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveLeaveBalanceAsync(){if(Selected is null){Message="Selecione um colaborador.";return;}try{await _service.SaveEmployeeLeaveBalanceAsync(new(_companyId,SelectedLeaveBalance?.Id,Selected.Id,LeaveYear,EntitledDays,CarriedDays,LeaveNotes));ClearLeaveBalance();await LoadLeaveBalancesAsync();Message="Saldo anual de férias guardado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task ArchiveLeaveBalanceAsync(){if(SelectedLeaveBalance is null){Message="Selecione um saldo de férias.";return;}try{await _service.ArchiveEmployeeLeaveBalanceAsync(_companyId,SelectedLeaveBalance.Id);ClearLeaveBalance();await LoadLeaveBalancesAsync();Message="Saldo de férias arquivado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task SavePayrollRuleAsync(){try{await _service.SavePayrollRuleAsync(new(_companyId,SelectedPayrollRule?.Id,PayrollRuleType,PayrollRuleName,PayrollRuleRate,PayrollRuleFixedAmount,PayrollRuleMinimumBase,PayrollRuleMaximumBase,PayrollRuleStartDate,PayrollRuleEndDate,PayrollRuleNotes));ClearPayrollRule();await LoadAsync();Message="Regra salarial guardada.";}catch(Exception ex){Message=ex.Message;}}
    private async Task ArchivePayrollRuleAsync(){if(SelectedPayrollRule is null){Message="Selecione uma regra salarial.";return;}try{await _service.ArchivePayrollRuleAsync(_companyId,SelectedPayrollRule.Id);ClearPayrollRule();await LoadAsync();Message="Regra salarial arquivada.";}catch(Exception ex){Message=ex.Message;}}
    private async Task LoadEmployeeLoansAsync(){EmployeeLoans.Clear();if(Selected is null)return;try{var rows=await _service.ListEmployeeLoansAsync(_companyId,Selected.Id);foreach(var row in rows)EmployeeLoans.Add(row);}catch(Exception ex){Message=ex.Message;}}
    private async Task SaveLoanAsync(){if(Selected is null){Message="Selecione um colaborador.";return;}try{await _service.SaveEmployeeLoanAsync(new(_companyId,SelectedLoan?.Id,Selected.Id,LoanType,LoanReference,LoanGrantedDate,LoanOriginalAmount,LoanOutstandingBalance,LoanInstallmentAmount,LoanFirstDeductionDate,LoanNotes));ClearLoan();await LoadEmployeeLoansAsync();Message="Adiantamento ou empréstimo guardado.";}catch(Exception ex){Message=ex.Message;}}
    private async Task SetLoanStatusAsync(string status){if(SelectedLoan is null){Message="Selecione um adiantamento ou empréstimo.";return;}try{await _service.SetEmployeeLoanStatusAsync(_companyId,SelectedLoan.Id,status);ClearLoan();await LoadEmployeeLoansAsync();Message=$"Contrato {status.ToLowerInvariant()}.";}catch(Exception ex){Message=ex.Message;}}
    private async Task ArchiveLoanAsync(){if(SelectedLoan is null){Message="Selecione um adiantamento ou empréstimo.";return;}try{await _service.ArchiveEmployeeLoanAsync(_companyId,SelectedLoan.Id);ClearLoan();await LoadEmployeeLoansAsync();Message="Contrato liquidado arquivado.";}catch(Exception ex){Message=ex.Message;}}
    private void ApplyFilter(){var q=_all.AsEnumerable();if(!string.IsNullOrWhiteSpace(Search)){var t=Search.Trim();q=q.Where(x=>x.EmployeeNumber.Contains(t,StringComparison.OrdinalIgnoreCase)||x.FullName.Contains(t,StringComparison.OrdinalIgnoreCase)||x.Department.Contains(t,StringComparison.OrdinalIgnoreCase)||x.JobTitle.Contains(t,StringComparison.OrdinalIgnoreCase));}Employees.Clear();foreach(var row in q.OrderBy(x=>x.FullName))Employees.Add(row);RefreshDepartmentSummaries();NotifyIndicators();}
    private void RefreshDepartmentSummaries(){DepartmentSummaries.Clear();foreach(var group in _all.Where(x=>x.Status=="Ativo").GroupBy(x=>x.Department).OrderBy(x=>x.Key))DepartmentSummaries.Add(new HumanResourcesDepartmentSummary(group.Key,group.Count(),group.Sum(x=>x.BaseSalary),group.Sum(x=>x.Allowances),group.Sum(x=>x.Deductions),group.Sum(x=>x.NetMonthly)));}
    private void ExportEmployees(){if(ExportadorCsv.Exportar("rh-colaboradores.csv",["Número","Nome","Departamento","Função","Contrato","Salário-base","Subsídios","Descontos","Líquido","Estado"],Employees.Select(x=>(IReadOnlyList<string>)[x.EmployeeNumber,x.FullName,x.Department,x.JobTitle,x.ContractType,x.BaseSalary.ToString("N2"),x.Allowances.ToString("N2"),x.Deductions.ToString("N2"),x.NetMonthly.ToString("N2"),x.Status])))Message="Relatório de colaboradores exportado.";}
    private void ExportPayroll(){if(SelectedPayroll is null){Message="Selecione uma folha salarial.";return;}if(ExportadorCsv.Exportar($"rh-folha-{SelectedPayroll.PayrollYear}-{SelectedPayroll.PayrollMonth:00}.csv",["Número","Colaborador","Departamento","Base","Abonos","Bruto","Imposto","Segurança Social","Empréstimos","Descontos","Líquido","Pagamento"],PayrollLines.Select(x=>(IReadOnlyList<string>)[x.EmployeeNumber,x.EmployeeName,x.Department,x.BaseSalary.ToString("N2"),x.Allowances.ToString("N2"),x.GrossAmount.ToString("N2"),x.IncomeTax.ToString("N2"),x.EmployeeSocialSecurity.ToString("N2"),x.LoanDeduction.ToString("N2"),x.Deductions.ToString("N2"),x.NetAmount.ToString("N2"),x.PaymentStatus])))Message="Folha salarial exportada.";}
    private void ExportDepartments(){if(ExportadorCsv.Exportar("rh-custos-por-departamento.csv",["Departamento","Colaboradores","Salários-base","Subsídios","Descontos","Líquido mensal"],DepartmentSummaries.Select(x=>(IReadOnlyList<string>)[x.Department,x.EmployeeCount.ToString(),x.BaseSalary.ToString("N2"),x.Allowances.ToString("N2"),x.Deductions.ToString("N2"),x.NetAmount.ToString("N2")])))Message="Relatório por departamento exportado.";}
    private void LoadForm(EmployeeFinancialRow x){EmployeeNumber=x.EmployeeNumber;FullName=x.FullName;TaxId=x.TaxId;SocialSecurityNumber=x.SocialSecurityNumber;Department=x.Department;CostCenter=x.CostCenter;JobTitle=x.JobTitle;ContractType=x.ContractType;HireDate=x.HireDate;EndDate=x.EndDate;BaseSalary=x.BaseSalary;Allowances=x.Allowances;Deductions=x.Deductions;BankName=x.BankName;Iban=x.Iban;Status=x.Status;Notes=x.Notes;}
    private void ClearForm(){Selected=null;EmployeeNumber=FullName=TaxId=SocialSecurityNumber=Department=CostCenter=JobTitle=BankName=Iban=Notes="";ContractType="Efetivo";Status="Ativo";HireDate=DateTime.Today;EndDate=null;BaseSalary=Allowances=Deductions=0;}
    private void ClearPayment(){SelectedPayrollLine=null;PaymentDate=DateTime.Today;PaymentReference=PaymentNotes="";}
    private void LoadAdjustment(EmployeeAdjustmentRow x){AdjustmentType=x.AdjustmentType;AdjustmentCategory=x.Category;AdjustmentDescription=x.Description;AdjustmentAmount=x.Amount;AdjustmentStartDate=x.StartDate;AdjustmentEndDate=x.EndDate;AdjustmentRecurring=x.Recurring;AdjustmentNotes=x.Notes;}
    private void ClearAdjustment(){SelectedAdjustment=null;AdjustmentType="Abono";AdjustmentCategory="Subsídio";AdjustmentDescription=AdjustmentNotes="";AdjustmentAmount=0;AdjustmentStartDate=DateTime.Today;AdjustmentEndDate=null;AdjustmentRecurring=true;}
    private void LoadAbsence(EmployeeAbsenceRow x){AbsenceType=x.AbsenceType;AbsenceStartDate=x.StartDate;AbsenceEndDate=x.EndDate;AbsenceDays=x.Days;AbsencePaid=x.Paid;AbsenceDeduction=x.DeductionAmount;AbsenceReason=x.Reason;AbsenceNotes=x.Notes;}
    private void ClearAbsence(){SelectedAbsence=null;AbsenceType="Férias";AbsenceStartDate=AbsenceEndDate=DateTime.Today;AbsenceDays=1;AbsencePaid=true;AbsenceDeduction=0;AbsenceReason=AbsenceNotes="";}
    private void LoadAttendance(EmployeeAttendanceRow x){AttendanceDate=x.WorkDate;EntryTime=x.EntryTime.ToString(@"hh\:mm");ExitTime=x.ExitTime?.ToString(@"hh\:mm")??"";RegularHours=x.RegularHours;OvertimeHours=x.OvertimeHours;OvertimeAmount=x.OvertimeAmount;AttendanceNotes=x.Notes;}
    private void ClearAttendance(){SelectedAttendance=null;AttendanceDate=DateTime.Today;EntryTime="08:00";ExitTime="17:00";RegularHours=8;OvertimeHours=OvertimeAmount=0;AttendanceNotes="";}
    private void LoadLeaveBalance(EmployeeLeaveBalanceRow x){LeaveYear=x.LeaveYear;EntitledDays=x.EntitledDays;CarriedDays=x.CarriedDays;LeaveNotes=x.Notes;}
    private void ClearLeaveBalance(){SelectedLeaveBalance=null;LeaveYear=DateTime.Today.Year;EntitledDays=22;CarriedDays=0;LeaveNotes="";}
    private void LoadPayrollRule(PayrollRuleRow x){PayrollRuleType=x.RuleType;PayrollRuleName=x.Name;PayrollRuleRate=x.Rate;PayrollRuleFixedAmount=x.FixedAmount;PayrollRuleMinimumBase=x.MinimumBase;PayrollRuleMaximumBase=x.MaximumBase;PayrollRuleStartDate=x.StartDate;PayrollRuleEndDate=x.EndDate;PayrollRuleNotes=x.Notes;}
    private void ClearPayrollRule(){SelectedPayrollRule=null;PayrollRuleType="Imposto salarial";PayrollRuleName=PayrollRuleNotes="";PayrollRuleRate=PayrollRuleFixedAmount=PayrollRuleMinimumBase=0;PayrollRuleMaximumBase=null;PayrollRuleStartDate=new DateTime(DateTime.Today.Year,1,1);PayrollRuleEndDate=null;}
    private void LoadLoan(EmployeeLoanRow x){LoanType=x.LoanType;LoanReference=x.Reference;LoanGrantedDate=x.GrantedDate;LoanOriginalAmount=x.OriginalAmount;LoanOutstandingBalance=x.OutstandingBalance;LoanInstallmentAmount=x.InstallmentAmount;LoanFirstDeductionDate=x.FirstDeductionDate;LoanNotes=x.Notes;}
    private void ClearLoan(){SelectedLoan=null;LoanType="Adiantamento salarial";LoanReference=LoanNotes="";LoanGrantedDate=DateTime.Today;LoanFirstDeductionDate=new DateTime(DateTime.Today.Year,DateTime.Today.Month,1).AddMonths(1);LoanOriginalAmount=LoanOutstandingBalance=LoanInstallmentAmount=0;}
    private void NotifyIndicators(){foreach(var p in new[]{nameof(ActiveEmployees),nameof(TotalBaseSalary),nameof(TotalAllowances),nameof(NetMonthlyPayroll)})OnPropertyChanged(p);}
}

public sealed record HumanResourcesDepartmentSummary(string Department,int EmployeeCount,
    decimal BaseSalary,decimal Allowances,decimal Deductions,decimal NetAmount);
