using System.Collections.ObjectModel; using System.Globalization; using System.Windows.Input; using FinancePro.Core.DTOs; using FinancePro.Core.Enums; using FinancePro.Services.Interfaces; using FinancePro.UI.Common;
namespace FinancePro.UI.ViewModels;
public class StockViewModel : ViewModelBase
{
 readonly IStockService _service; readonly int _empresaId; string _codigo="",_nome="",_categoria="",_unidade="UN",_minimo="0",_localizacao="",_quantidade="",_custo="",_documento="",_mensagem=""; ProdutoStockDto? _produto; TipoMovimentoStock _tipo=TipoMovimentoStock.Entrada;
 public ObservableCollection<ProdutoStockDto> Produtos{get;}=new(); public ObservableCollection<MovimentoStockDto> Movimentos{get;}=new(); public IReadOnlyList<TipoMovimentoStock> Tipos{get;}=Enum.GetValues<TipoMovimentoStock>();
 public string Codigo{get=>_codigo;set=>SetProperty(ref _codigo,value);} public string Nome{get=>_nome;set=>SetProperty(ref _nome,value);} public string Categoria{get=>_categoria;set=>SetProperty(ref _categoria,value);} public string Unidade{get=>_unidade;set=>SetProperty(ref _unidade,value);} public string Minimo{get=>_minimo;set=>SetProperty(ref _minimo,value);} public string Localizacao{get=>_localizacao;set=>SetProperty(ref _localizacao,value);} public string Quantidade{get=>_quantidade;set=>SetProperty(ref _quantidade,value);} public string Custo{get=>_custo;set=>SetProperty(ref _custo,value);} public string Documento{get=>_documento;set=>SetProperty(ref _documento,value);} public string Mensagem{get=>_mensagem;set=>SetProperty(ref _mensagem,value);} public ProdutoStockDto? ProdutoSelecionado{get=>_produto;set=>SetProperty(ref _produto,value);} public TipoMovimentoStock Tipo{get=>_tipo;set=>SetProperty(ref _tipo,value);}
 public decimal ValorTotalStock=>Produtos.Sum(x=>x.ValorStock); public int Alertas=>Produtos.Count(x=>x.AbaixoMinimo);
 public ICommand CriarProdutoCommand{get;} public ICommand MovimentarCommand{get;} public ICommand AtualizarCommand{get;}
 public StockViewModel(IStockService s,int e){_service=s;_empresaId=e; CriarProdutoCommand=new AsyncRelayCommand(_=>Criar()); MovimentarCommand=new AsyncRelayCommand(_=>Movimentar()); AtualizarCommand=new AsyncRelayCommand(_=>Carregar()); _=Carregar();}
 async Task Carregar(){try{var ps=await _service.ListarProdutosAsync(_empresaId); Produtos.Clear();foreach(var x in ps)Produtos.Add(x);var ms=await _service.ListarMovimentosAsync(_empresaId);Movimentos.Clear();foreach(var x in ms)Movimentos.Add(x);OnPropertyChanged(nameof(ValorTotalStock));OnPropertyChanged(nameof(Alertas));}catch(Exception ex){Mensagem=ex.Message;}}
 static decimal Dec(string s)=>decimal.TryParse(s,NumberStyles.Any,CultureInfo.CurrentCulture,out var v)||decimal.TryParse(s,NumberStyles.Any,CultureInfo.InvariantCulture,out v)?v:0;
 async Task Criar(){try{await _service.CriarProdutoAsync(new NovoProdutoDto{EmpresaId=_empresaId,Codigo=Codigo,Nome=Nome,Categoria=Categoria,Unidade=Unidade,StockMinimo=Dec(Minimo),Localizacao=Localizacao});Mensagem="Produto criado com sucesso.";Codigo=Nome=Categoria=Localizacao="";await Carregar();}catch(Exception ex){Mensagem=ex.Message;}}
 async Task Movimentar(){try{if(ProdutoSelecionado==null)throw new InvalidOperationException("Selecione um produto.");await _service.MovimentarAsync(new NovoMovimentoStockDto{EmpresaId=_empresaId,ProdutoId=ProdutoSelecionado.Id,Tipo=Tipo,Quantidade=Dec(Quantidade),CustoUnitario=Dec(Custo),DocumentoReferencia=Documento});Mensagem="Movimento registado com sucesso.";Quantidade=Custo=Documento="";await Carregar();}catch(Exception ex){Mensagem=ex.Message;}}
}
